name: 18F eslint
description: Runs eslint using the 18F standard configuration on a set of files
inputs:
  lint-glob:
    description: Path glob to run eslint against. Defaults to the project root if empty.
    required: false
    default: .
  only-changed:
    description: Whether to limit linting to just the changed files. Must be "true" to enable. Overrides lint-glob, if provided.
    required: false
    default: false
  working-directory:
    description: The working directory to begin from. This should be the directory that contains your package.json.
    required: false
    default: .
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.working-directory }}
    - ${{ inputs.lint-glob }}
    - ${{ inputs.only-changed }}
